### ISSUE TITLE
Po otvorení tasku s filtra sa vyresetuje nastavenie filtra

### ISSUE THREAD

**Issue by bsusta** [bsusta/lanhelpdesk-nasadenie#15]
Nastavenie filtra v FILTER prihláseného používateľa by si mal systém pamätať, pokým používateľ nestlačí RESET.

Nastavenie filtra by sa malo uložiť pri stlačení APPLY FILTER a to:
Varianta A do REDUXU - po odhlasení používatela sa sa nastavenie FILTRA stratí
Varianta B do nastavenia prihlaseného používatela  - nastavenie sa zachová po prihlasení a odhlasení používatela
Nastavenie filtra sa vymaže po stlačení RESET

**Comment by Corrigan14** [comment]
Done: 

Url vracajuce pouzivateov zapamatany filter: GET: /api/v1/task-bundle/filters/user-remembered
Url ukladajuca tento filter: POST: /api/v1/task-bundle/filters/user-remembered
Url mazajuca tento filter: DELETE: /api/v1/task-bundle/filters/user-remembered

Dufam ze som nieco nerozbabrala tymto :) keby len napis

**Comment by bsusta** [comment]
Testoval som to, funguje to po APPLY FILTER sa filter uloží.
