### ISSUE TITLE
Pridať označenie READ-ONLY taskov v taskliste pre prihlaseného použivatela

### ISSUE THREAD

**Issue by bsusta** [bsusta/lanhelpdesk-nasadenie#16]
Tasky ku ktorým nemá prihlasený používatel oprávnenie resolve (editáciu) ale len view by mali byť označené v task liste READ ONLY. Stačí vedla názvu do zatvorky (READ ONLY) ja by som to už naštíloval

**Comment by jurajch** [comment]
martinka, potrebujem v task liste zikat ku kazdemu tasku aj canEdit - tak ako je to pri jednom tasku. malo by to prihliadat na aclko roly prihlaseneho uzivatela a aj na projektove acl.

**Comment by Corrigan14** [comment]
Done :)

**Comment by jurajch** [comment]
funguje, brano, odskusaj

**Comment by bsusta** [comment]
Ok. Funguje to
