### ISSUE TITLE
Doplniť do filtra možnosť pri CREATED, REQUESTER, ASSIGNED zadať LOGGED USER #18

### ISSUE THREAD

**Issue by bsusta** [bsusta/lanhelpdesk-nasadenie#26]
Filter by bral ako parameter do filtrovania pri vybratí LOGGED USER prihlaseného používatela.

**Comment by jurajch** [comment]
martinka, prosim ta, vedela by si prosim poslat z task-bundle/filters/options aj "current-user" do created, requester a assigned? myslim, ze id by malo byt "current-user" a username nieco zrozumitelne kedze sa to bude zobrazovat v tom dropdowne vo filtri...

**Comment by jurajch** [comment]
mne to uz funguje fajn. brano, otestuj to potom...

**Comment by bsusta** [comment]
vyzerá že to funguje ok
