### ISSUE TITLE
Task vytvorený uživatelom customer nemá defaultný status NEW

### ISSUE THREAD

**Issue by bsusta** [bsusta/lanhelpdesk-nasadenie#28]
Uživatel customer vytvoril task 69092: Task from customer 20.9.2017, tento task nemá status NEW.
Každý nový task má mať defaultný status NEW

**Comment by jurajch** [comment]
mne to funguje. brano, otestuj.

**Comment by bsusta** [comment]
Funguje to. Ale keď premenujem status NEW napr na Novy tak to nefunguje a vypisuje to error.
Systém by mal prideliť novému tasku, status s orderom 1.

**Comment by jurajch** [comment]
to je skor vec apiny
