### ISSUE TITLE
Firmy majú mať tel. číslo

### ISSUE THREAD

**Issue by ladislavbili** [bsusta/lanhelpdesk-nasadenie#36]
Companies majú mať premennú telefónne číslo. Neviem či už je implementovaná cez companyData alebo ju treba pridať defaultne.

**Comment by Corrigan14** [comment]
mozne pridat cez COMPANY DATA (pozri ERD v prilohe
![erd-hd](https://user-images.githubusercontent.com/27185255/31043449-21d43476-a5bc-11e7-92e2-34e6e26f1af9.png)
)
