### ISSUE TITLE
Firma má mať premennú subscription time

### ISSUE THREAD

**Issue by ladislavbili** [bsusta/lanhelpdesk-nasadenie#37]
Firma má mať premennú subscriptionTime, ktorá bude celé číslo

**Comment by Corrigan14** [comment]
Mozne pridat cez COMPANY DATA  - pozri ERD model
![erd-hd](https://user-images.githubusercontent.com/27185255/31043455-54cd36e8-a5bc-11e7-93fd-410e094ee84f.png)
