### ISSUE TITLE
POSTing data

### ISSUE THREAD

**Issue by ladislavbili** [bsusta/lanhelpdesk-nasadenie#40]
Chápem, že ak získavam data v GET requeste, tak posielam data v url napríklad
https://dev.lanhelpdesk.com/api/v1/task-bundle/tasks/1 
ale ak postujem data, tak ich POSTnem bud to sposobom
`        method: 'POST',
        headers: {'Content-Type': 'application/x-www-form-urlencoded'},
        body: `username=${username}&password=${password}`
`
ktorý funguje ale treba vypisovat vsetky data
alebo priamo ako JSON
`        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({username,password})
`
pricom postovanie jsonu nefunuje, pri prihlasovani napise ze pouzivatel neexistuje, pri pridavani novej firmy ze som nevyplnil pole title ktore som si isty ze v JSONe je (vypisal som si ho pri errore a bol tam). Preto nechápem, ako api posielat JSON súbory.

**Comment by Corrigan14** [comment]
Ahoj,

Parametre, ktore su naviazane na ine entity sa posielaju v URL adrese cize cez HEADERS. Ostatne [arametre posielas ako zakodovany JSON cez telo.
