### ISSUE TITLE
User data

### ISSUE THREAD

**Issue by ladislavbili** [bsusta/lanhelpdesk-nasadenie#41]
Ešte mám otázku, ako sa nakoniec rieši to, aby ked sa user prihlasil dostal všetky data o sebe? 
neviem o tom že by ich momentálne získaval ked volám (/token-authentication), jediné čo mi API vráti pri logine len token. Mám teda získavať info o pouzivatelovi zvlast po prihlaseni dalsim volanim cez (/users/{id})?

**Comment by jurajch** [comment]
ono v tom tokene su vsetky data. pouziva sa nejaka kniznica jwt-decode.
takto to je u mna na fronte:

import jwtDecode from 'jwt-decode';

function *login(action) {
    try {
        const response = yield call(apiLogin, action.data);
        const token = response.token; // <- tu dostanes token, z toho callu vyssie
        const decoded = jwtDecode(token); // <- tu ho dekodnes - je to objekt, kde su user data
        yield put(loginSucces(response.token, decoded)); // <- tu sa ulozi niekde (do reduxu?)
    } catch (e) {
        yield put(loginError(e.message));
    }
}
