### ISSUE TITLE
Vyxportovať front z reactu na nasadenie frontu na webhosting

### ISSUE THREAD

**Issue by bsusta** [bsusta/lanhelpdesk-nasadenie#44]
@jurajch 
1. Exportovať front z reactu na webhosting
2. Spísať postup exportu z reactu na export na front
3. Spísať požiadavky na webhosting - čo musím splnať aby fungoval na nom front
@bsusta
Nasadiť export frontu na webhosting

**Comment by jurajch** [comment]
staci v konzole napisat:npm run build
a v subore build sa vygeneruje cely projekt. to potom staci hodit na hosting. hosting nemusi splnat nic, kedze je to iba html a js.
