### ISSUE TITLE
Otvorenie menu sidebar funguje len naboku + v mini sidebare nefunguje vôbec

### ISSUE THREAD

**Issue by bsusta** [bsusta/lanhelpdesk-nasadenie#49]
1. V sidebare odkaz na otvorenenie menu prekrýva ikona a nazov menu aj ked sú vo vnútri odkazu
2. v mini sidebare vôbec nefunguje otvorenie menu

**Comment by bsusta** [comment]
Testoval som kde je problém. A chyba je v funkcii  menuToggleActive(). Ona funguje tak že testuje classname html tagu na ktorý sa klikne. Problém je že to testuje vnorené komponenty odkazu na ktorý sa klika.  My potrebujeme manipulovať z classami hlavného odkazu a nie z vnorenými komponentami.
Každé podmenu ma premenú ktorá drží info o tom čí je podmenu otvorené. My by sme potrebovali meniť túto hodnotu.

const mytasksOpen = true;
  const filtersOpen = true;
  const projectsOpen = true;
  const archivedProjectsOpen = false;
  const tagsOpen = false;
  const reportsOpen = false;

    menuToggleActive = (e) => {

        if (e.target.classList.contains('active')) {
            e.target.classList.remove('active');
        } else {
            e.target.classList.add('active');
        }

    };

**Comment by jurajch** [comment]
otestovat

**Comment by bsusta** [comment]
funguje to. PS: Nahraj to prosím ta aj na http://lanhelpdesk4.lansystems.sk
