### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by ladislavbili** [bsusta/lanhelpdesk-nasadenie#56]
Mám dve otázky: 
Kde na API sa dá vytvárať nový user?
Kde updatujem userove údaje? Skusal som pouzivat PATCH /api/v1/core-bundle/users/{id} ale nefungovalo mi to. Uz priamo na stranke ked som vlozil token, id pouzivatela (2406) a napisal mu nejaky parameter ako surname a dal try vratilo to chybu.

**Comment by jurajch** [comment]
usera vytvaras na adrese /api/v1/core-bundle/users/user-role/{$userroleid}/company/{$companyid}
tusim email, password, username su povinne parametre + userrole a company v adrese

je to post, parametre vo form-data

**Comment by jurajch** [comment]
update na /api/v1/core-bundle/users/{userid}
pripadne zas na /api/v1/core-bundle/users/{userid}/user-role/{$userroleid}/company/{$companyid}

PUT, application/x-www-form-urlencoded, 
data sa prezenu cez modul **queryString**.stringify(data)
