### ISSUE TITLE
Datetime - test

### ISSUE THREAD

**Issue by Corrigan14** [bsusta/lanhelpdesk-nasadenie#57]
Ahojte,

Vyjadrite sa prosim k Tasku #9 :)

**Comment by jurajch** [comment]
ja som na tom stravil cely piatok, ale este neviem, ci je to ok. resp. timestamp je ok, ale robi mi to este haluze s timezones. skusim to dnes objasnit

**Comment by bsusta** [comment]
Laco skontroluj si či ti tento formát dátumu vyhovuje !!!

**Comment by ladislavbili** [comment]
Skusal som to implementovat, momentalne sa vytvara task a odosiela deadline v tomto formate, vsetko prebieha ok, task sa vytvori atd, ale ked ho ziskam z  GET tak uz ma zas format ako bol ten predtym. Typujem ze toto este bude dorobene na strane api
UPDATE: uz vracia c: prave som to skusal este raz
