### ISSUE TITLE
Doplnit do dokumentácie API vzor requestov

### ISSUE THREAD

**Issue by ladislavbili** [bsusta/lanhelpdesk-nasadenie#58]
Doplnit do dokumentacie API priklad API callu, aby ku vsetkemu bola kombinacia request, response napríklad:

REQUEST:
https://dev.lanhelpdesk.com/api/v1/token-authentication,
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/x-www-form-urlencoded'
        },
        method: 'POST',
        body:'username=aaa&password=bbb',
      })

RESPONSE:
{
  "token": "eyJhbGciOiJSUzI1NiJ9.eyJpZCI6MjMwMCwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AYWRta6LzteHavMWV9OUg"
}

**Primarne pre post Tasku a userov**

**Comment by Corrigan14** [comment]
Pozri task #69 ..je to takto ok?
