### ISSUE TITLE
Po nastavení tasku do stavu closed sa nenastaví čas closed at

### ISSUE THREAD

**Issue by bsusta** [bsusta/lanhelpdesk-nasadenie#66]

**Comment by Corrigan14** [comment]
Dorobit do status tabulky policko default a function: 
- defaultne nie su updatovatelne function pre: NEW, CLOSED, IN PROGRESS, PENDING

Dorobit do ERD:
- tabulku task has status: tato musi obsiahnut cas kedy bol status pridany, GPS, User ID ktory zmenil tento status

**Comment by Corrigan14** [comment]
done
