### ISSUE TITLE
Pridat potvrdenie modálne okno vymazania 

### ISSUE THREAD

**Issue by bsusta** [bsusta/lanhelpdesk-nasadenie#68]
Do you really want to delete the filter?
CANCEL                                    YES

**Comment by bsusta** [comment]
Testoval som to ale filter sa vymaže bez toho aby sa ukázalo modálne okno.
Nahral si to do mastra ?

**Comment by jurajch** [comment]
skus teraz

**Comment by bsusta** [comment]
odtestovane funguje
