### ISSUE TITLE
Standard pre posielanie JSON Data

### ISSUE THREAD

**Issue by Corrigan14** [bsusta/lanhelpdesk-nasadenie#75]
http://www.json.org/

Ak to niekde nie je takto urobene posli mi prosim task a ja to zmenim

**Comment by ladislavbili** [comment]
Po prvom stretnuti som riesil problem s odosielanim JSON dat pri POST PUT alebo PATCH, nasledne pri telefonate v ktorom bol myslim aj juraj mi bolo povedane, ze najlepsie asi bude, ak budu data parsovane do 'Content-Type': 'application/x-www-form-urlencoded', co som aj spravil pomocou vlastneho parseru a data z mobilnej apky sa uz v tomto formate do REST api odosielaju a nie je s tym problem.
