### ISSUE TITLE
DATETIME

### ISSUE THREAD

**Issue by bsusta** [bsusta/lanhelpdesk-nasadenie#9]
Cas zmenit na currentmills

**Comment by bsusta** [comment]
Pridal som Vás všetkých k tomuto tasku, lebo sa to týka všetkých.
Martina pozerala na ten datetime a ona používa štandardný formát v php.
Nenašla priamo v PHP datetime.
http://php.net/manual/en/class.datetime.php

Ja som sa na to pozeral a to čo chcete je formát času v timestamp ?
http://php.net/manual/en/datetime.gettimestamp.php

Aj s tým sú spojené nejaké problémy vid. komentáre v članku k php timestamp.

**Comment by jurajch** [comment]
mne sa tie problemy v komentaroch zdaju byt irelevantne

**Comment by bsusta** [comment]
http://php.net/manual/en/datetime.gettimestamp.php

**Comment by ladislavbili** [comment]
Issue je hlavne v tom, ze PHP vytvara sice timespamp ale co som si skusal runnut maly php kod, tak vratil timestamp orezany o 3 posledne miesta. Niekto iny kto to skusil a dostal podobny vysledok? pretoze ak je toto chyba php timestampu tak bude potrebne na koniec vzdy pridat 3 nuly nech je to ekvivalentne s javascriptom

**Comment by Corrigan14** [comment]
Takze: urobila som zmenu datumu na TASK LIST-e do toho formatu TIMESTAMP. Tyka sa to datumov: createdAt, updatedAt, deadline, startedAt a closedAt.  Prosim pozrite to a napiste mi ci je to ok. Ak ano urobim tuto zmenu pri vsetkych datumoch v systeme.

**Comment by jurajch** [comment]
pre mna je to ok, ale je mi to zaroven aj jedno, ci to bude timestamp alebo datetime.

**Comment by jurajch** [comment]
pre mna je to ok, ale moze to byt kludne aj datetime. je mi to jedno

**Comment by Corrigan14** [comment]
timestamp som uz nastavila aj pre tabulku task_has_assigned_uaser

**Comment by bsusta** [comment]
S Lacovej strany je ten formát dátumu OK. Takže to môžeš spraviť aj na ostatných dátumoch.
Budeme to ukladať v SQL v datetime UTC 0  a v API dávať v timestampoch ?

**Comment by Corrigan14** [comment]
Zo strany api sa uz vsetky date-y prijimaju vo formate Timestamp a zaroven sa v tomto formate vracaju
